Revert "Add volume mounts to access tools exports"
This is breaking the silverpop export locally. I think it's
mounting over tmp and preventing the lock files being written
in the container as a result. e.g.

jack@debian:~/fundraising-dev$ ./scripts/silverpop-update.sh
Begin Silverpop Update
Traceback (most recent call last):
  File "/srv/tools/silverpop_export/update.py", line 121, in <module>
    lock.begin()
  File "/srv/tools/process/lock.py", line 45, in begin
    f = open(filename, "w")
        ^^^^^^^^^^^^^^^^^^^
PermissionError: [Errno 13] Permission denied: '/tmp/fundraising-tools-update.py.lock'

I'll add a convenience script to let us see the exported files as a workaround.

This reverts commit c1ce70b68e8250409a4a4d548500fcd0671419ef.

Change-Id: Id968829f74cce9e375f9cda901db55fa5daa8254